//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorTracer
    {
        public int iErrorID { get; set; }
        public Nullable<int> vErrorNumber { get; set; }
        public Nullable<int> vErrorState { get; set; }
        public Nullable<int> vErrorSeverity { get; set; }
        public Nullable<int> vErrorLine { get; set; }
        public string vErrorProc { get; set; }
        public string vErrorMsg { get; set; }
        public string vUserName { get; set; }
        public string vHostName { get; set; }
        public Nullable<System.DateTime> dErrorDate { get; set; }
    }
}
