//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTutorials
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Nullable<int> CategoryId { get; set; }
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
