//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTutorials
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUEST
    {
        public int ID { get; set; }
        public Nullable<int> customerID { get; set; }
        public string requestContent { get; set; }
        public System.DateTime requestDate { get; set; }
        public Nullable<System.DateTime> completedDate { get; set; }
        public string status { get; set; }
        public string comment { get; set; }
        public string IsNotifiedToCustomer { get; set; }
        public string IsNotifiedToTechnician { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
