//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTutorials
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmallCategory
    {
        public string Id { get; set; }
        public string Big_Id { get; set; }
        public string Name { get; set; }
    
        public virtual BigCategory BigCategory { get; set; }
    }
}
